### ISSUE TITLE
安装报错。

### ISSUE THREAD

**Issue by Effie123** [Qinmei/qinVideo#84]
在执行  `npm run dev`  时出现如下错误。
> npm run dev

> qinvideo-node@1.0.0 dev /node/qinvideo
    egg-bin dev
[egg-ts-helper] create typings/app/extend/helper.d.ts (2ms)
[egg-ts-helper] create typings/app/controller/index.d.ts (3ms)
[egg-ts-helper] create typings/app/middleware/index.d.ts (1ms)
[egg-ts-helper] create typings/app/model/index.d.ts (1ms)
[egg-ts-helper] create typings/config/index.d.ts (12ms)
[egg-ts-helper] create typings/config/plugin.d.ts (1ms)
[egg-ts-helper] create typings/app/service/index.d.ts (2ms)
[egg-ts-helper] create typings/app/index.d.ts (0ms)
2020-06-29 19:09:13,443 INFO 22186 [master] node version v12.18.1
2020-06-29 19:09:13,445 INFO 22186 [master] egg version 2.26.1
2020-06-29 19:09:14,506 INFO 22186 [master] agent_worker#1:22204 started (1057ms)
/node/qinvideo/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: [egg-core] load file: /node/qinvideo/app/service/count.ts, error: ⨯ Unable to compile TypeScript:
app/service/count.ts(60,40): error TS2769: No overload matches this call.
  Overload 1 of 2, '(conditions: MongooseFilterQuery<Pick<any, string | number | symbol>>, doc: MongooseUpdateQuery<Pick<any, string | number | symbol>>, callback?: ((err: any, raw: any) => void) | undefined): Query<...>', gave the following error.
    Argument of type '{ $inc: { [x: string]: number; }; }' is not assignable to parameter of type 'MongooseUpdateQuery<Pick<any, string | number | symbol>>'.
      Type '{ $inc: { [x: string]: number; }; }' is not assignable to type 'UpdateQuery<Pick<any, string | number | symbol>>'.
        Types of property '$inc' are incompatible.
          Type '{ [x: string]: number; }' is not assignable to type 'OnlyFieldsOfType<Pick<any, string | number | symbol>, number | undefined, number | undefined>'.
            Type '{ [x: string]: number; }' is not assignable to type 'NotAcceptedFields<Pick<any, string | number | symbol>, number | undefined>'.
              Index signatures are incompatible.
                Type 'number' is not assignable to type 'undefined'.
  Overload 2 of 2, '(conditions: MongooseFilterQuery<Pick<any, string | number | symbol>>, doc: MongooseUpdateQuery<Pick<any, string | number | symbol>>, options: ModelUpdateOptions, callback?: ((err: any, raw: any) => void) | undefined): Query<...>', gave the following error.
    Argument of type '{ $inc: { [x: string]: number; }; }' is not assignable to parameter of type 'MongooseUpdateQuery<Pick<any, string | number | symbol>>'.
      Type '{ $inc: { [x: string]: number; }; }' is not assignable to type 'UpdateQuery<Pick<any, string | number | symbol>>'.
    at createTSError (/node/qinvideo/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/node/qinvideo/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/node/qinvideo/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/node/qinvideo/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.require.extensions.<computed> [as .ts] (/node/qinvideo/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.loadFile (/node/qinvideo/node_modules/egg-core/lib/utils/index.js:27:19)
    at getExports (/node/qinvideo/node_modules/egg-core/lib/loader/file_loader.js:199:23)
    at ContextLoader.parse (/node/qinvideo/node_modules/egg-core/lib/loader/file_loader.js:158:25)
    at ContextLoader.load (/node/qinvideo/node_modules/egg-core/lib/loader/file_loader.js:67:24)
    at AppWorkerLoader.loadToContext (/node/qinvideo/node_modules/egg-core/lib/loader/egg_loader.js:408:28)
    at AppWorkerLoader.loadService (/node/qinvideo/node_modules/egg-core/lib/loader/mixin/service.js:24:10)
[2020-06-29 19:09:20.573] [cfork:master:22186] worker:22215 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2020-06-29 19:09:20.573] [cfork:master:22186] don't fork, because worker:22215 will be kill soon
2020-06-29 19:09:20,573 INFO 22186 [master] app_worker#1:22215 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2020-06-29 19:09:20.574] [cfork:master:22186] worker:22215 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2020-06-29 19:09:20,579 ERROR 22186 nodejs.AppWorkerDiedError: [master] app_worker#1:22215 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/node/qinvideo/node_modules/egg-cluster/lib/master.js:510:21)
    at Master.emit (events.js:315:20)
    at Messenger.sendToMaster (/node/qinvideo/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/node/qinvideo/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.<anonymous> (/node/qinvideo/node_modules/egg-cluster/lib/master.js:353:22)
    at EventEmitter.emit (events.js:327:22)
    at ChildProcess.<anonymous> (internal/cluster/master.js:191:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
name: "AppWorkerDiedError"
pid: 22186
hostname: server
2020-06-29 19:09:20,586 ERROR 22186 [master] app_worker#1:22215 start fail, exiting with code:1
2020-06-29 19:09:20,587 ERROR 22186 [master] exit with code:1
2020-06-29 19:09:20,597 ERROR 22204 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2020-06-29 19:09:20,605 ERROR 22204 [agent_worker] exit with code:110
Error: /node/qinvideo/node_modules/egg-bin/lib/start-cluster {"typescript":true,"declarations":true,"workers":1,"baseDir":"/node/qinvideo","framework":"/node/qinvideo/node_modules/egg"} exit with code 1
    at ChildProcess.<anonymous> (/node/qinvideo/node_modules/common-bin/lib/helper.js:56:21)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  code: 1
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qinvideo-node@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the qinvideo-node@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-29T11_09_20_636Z-debug.log

**Comment by Qinmei** [comment]
npm的安装有点问题；

你先使用`npm i -g yarn`, 然后后续的`npm dev` 这种命令里面的`npm`都换成`yarn`

`yarn`, `yarn dev` , `yarn start` 这样，后续我再详细测试下
